version: 2.1

orbs:
  codecov: codecov/codecov@3.1.1

executors:
  contracts:
    docker:
      - image: cimg/node:lts
      
jobs:
  build-and-test:
    environment:
      ENABLE_GAS_REPORT: 'true'
    executor: contracts
    steps:
      - checkout
      - run:
          name: Build SDK
          command: |
            cd sdk
            npm install
            npm run build
      - run:
          name: Test sol contracts
          command: |
            cd contracts
            npm install
            npm test
      - codecov/upload:
          file: './coverage/lcov.info'
workflows:
  contracts:
    jobs:
      - build-and-test